### ISSUE TITLE
Necessity of "static" prefix for functions.

### ISSUE THREAD

**Issue by Loufe** [verillious/godot-datetime#12]
Hi there,

Was hoping to discuss the need for "static"ally defined functions. I'm living with constants warnings in my project due to the way I use the plugin, was hoping to get some insight.

I start from year 0 in my game, so I need to seed DateTime object with time 0. The "from_timestamp" function does this perfectly.
![image](https://github.com/user-attachments/assets/468a586b-4105-42f3-af87-30bbd92223b0)

I'm getting warnings doing this as the function is technically a static function.
![image](https://github.com/user-attachments/assets/965b8334-72af-4b9d-bf6c-b9dcbcb6ec85)

Verillious, would you be open to removing the static prefix? If not, what are your thoughts?

Thanks!

**Comment by verillious** [comment]
`from_timestamp` returns an instance - you don't need to create one to use it, hence why it's marked as static (`time = DateTime.from_timestamp(0)`)

**Comment by Loufe** [comment]
> `from_timestamp` returns an instance - you don't need to create one to use it, hence why it's marked as static (`time = DateTime.from_timestamp(0)`)

That explains it, thank you! Sorry for the dead weight issue and appreciate your time :

**Comment by verillious** [comment]
No worries at all!
