### ISSUE TITLE
Difference between two dates in days ?

### ISSUE THREAD

**Issue by afk-mario** [verillious/godot-datetime#2]
Is there a way to check the difference in days between to dates?

**Comment by verillious** [comment]
Hey @afk-mario there's no clean method to do this at the moment - I'm going to add a way to create a "delta" now! If you need it really quickly you can try this:

```
(datetime_02.epoch - datetime_01.epoch) / 86400
```

(there are 86400 seconds in a day and the [epoch](https://github.com/verillious/godot-datetime/wiki/DateTime#epoch) is stored in seconds)

**Comment by afk-mario** [comment]
Thanks! I manged to make it work with the standard Time class on Godot, just to clarify what I wanted to achieve was to tell if a day was the day after another date.

For example Monday at midnight is one day before Tuesday at 1am even if the difference is less than a day in seconds
