### ISSUE TITLE
Godot 4 Support

### ISSUE THREAD

**Issue by TheIgel69** [verillious/godot-datetime#3]
Hey, do you plan Godot 4 support in the near future?

**Comment by verillious** [comment]
I haven't had a chance to use Godot 4 yet but I don't imagine a Godot 4 version of this library would be too much work. I will take a look at some point this week and get back to you.

**Comment by TheIgel69** [comment]
The major change is the new _Time_ class. This provides now the time functions instead of _OS_
see: https://docs.godotengine.org/en/stable/classes/class_time.html

**Comment by verillious** [comment]
Took longer than expected (sorry) but here you go: https://github.com/verillious/godot-datetime/releases/tag/v1.0.0.g4

**Comment by verillious** [comment]
Release on the asset library is pending
