### ISSUE TITLE
how should i implement timezone support?

### ISSUE THREAD

**Issue by CollCaz** [verillious/godot-datetime#5]
So i added timezone support but im not sure how best to write it in the code

Would you like a new functions maybe called now_adjusted() or now_timezone_adjusted()?

Please tell me what to name the new function.

edit:
for now i added an optional argument for the now() function, it is set to false by default and if set to true the function will return time zone adjusted time stamp

This is my first time contributing to open source, sorry if this was a bit annoying.

**Comment by verillious** [comment]
No worries at all - let me know when you have a PR I can look at - thank you for working on it!

**Comment by CollCaz** [comment]
k

**Comment by CollCaz** [comment]
@verillious I submitted a pull request.
